posts/urls.py
# from django.urls import
from django.conf.urls import url
from posts.views import Index, Profile

# from . import views
from posts import views

urlpatterns = [
    # path('', views.Index, name='index'),
    # path('', Index.as_view(), name='index'),
    # path('', views.index, name='index'),
    #     path('', views.blog, name='blog'),
    # path('', Profile.as_view()),
        

    # re_path(r'^user/(\w+)/$', views.Profile, name='profile'),
    # url(r'^user/', Profile.as_view(), name='profile')
]

posts/models.py
# from django.db import models
from django.db import models
from user_profile.models import User

# Create your models here.
from django import forms

class Post(models.Model):
    #Post madel
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=300)
    created_date = models.DateTimeField(auto_now_add=True)
    location = models.CharField(max_length=31, default='Global')
    is_active = models.BooleanField(default=True)
    is_favorit = models.BooleanField(default=False)

    def __str__(self):
        return self.text[:48]

    # email = models.EmailField()
    # name = models.CharField(max_length=128)

class HashTag(models.Model):
    #Hashtag model
    name = models.CharField(max_length=123, unique=True)
    post = models.ManyToManyField(Post)

    def __str__(self):
        return self.name[:48]

posts/forms.py
from django import forms
# from .models import *


#
# class PostForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         exclude = [""]

class PostForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={'rows': 2, 'cols': 80}), max_length=300)

posts/views.py
# from django.shortcuts import render
# Create your views here.
from django.shortcuts import render
# from django.http import HttpResponse
from django.views import View
from .models import Post, HashTag
from user_profile.models import User
from posts.forms import PostForm
from django.http import HttpResponseRedirect


#
# def home(request):
#     return render(request, 'home.html', {})


class Index(View):

    def get(self, request):
        context = {'text': 'Посты по Django!!'}
        return render(request, 'home.html', context)


class Profile(View):
    # user profile Page http://127.0.0.1:8000/user/<username>
    def get(self, request, username):
        user = User.objects.get(username=username)
        posts = Post.objects.filter(user=user)
        form = PostForm()
        context = {
            'posts': posts,
            'user': user,
            'form': form,

        }
        return render(request, 'profile.html', context)


class PostPost(View):
    def post(self, request, username):
        form = PostForm(self.request.POST)
        if form.is_valid():
            user = User.objects.get(username=username)
            post = Post(text=form.cleaned_data['text'], user=user)
            post.save()
            words = form.cleaned_data['text'].split(" ")
            for word in words:
                if word.startswith('#'):
                    hash_tag, created = HashTag.objects.get_or_create(name=word)
                    hash_tag.post.add(post)
        return HttpResponseRedirect('/user/' + username)

posts/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>Starter Template for Bootstrap!</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!--Custom styles for this template -->
    <style type="text/css">
        body {
            padding-top: 5rem;
        }

        .starter-template {
            padding: 3rem 1.5rem;
            text-align: center;
        }

    </style>
</head>


<body>
    <!-- /nav bar -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'index' %}">Домой.</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Мой блог. <span class="sr-only">(current)</span></a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <!-- /end nav bar -->

    <div class="container">
        <div class="starter-template">
            <h1>{{ text }}</h1>

        </div>
    </div>
    <!-- /.container -->

    <!--  -->

    <!-- Content here -->
    <div class="container">
        {% block content %} {% endblock %}

    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <img src="{% static 'img/asd3.jpg' %}" alt="" class="mw-100">
            </div>
        </div>
    </div>

    <!-- /.page-section -->
    <!-- /.page-section -->

    <!--footer-->
    <div class="page-footer fut ">
        <footer class="footer-nav ">
            <div class="container">
                <div class="row">
                    <div class="col-xs-3 fut1">
                        <h4>Pricing</h4>
                        <ul>
                            <li><a href="/pricing/">Vultr Cloud Compute (VC2)</a></li>
                            <li><a href="/pricing/baremetal/">Bare Metal</a></li>
                            <li><a href="/pricing/blockstorage/">Block Storage</a></li>
                            <li><a href="/pricing/dedicatedcloud/">Dedicated Instances</a></li>
                            <li><a href="/ddos/">DDoSs Protection</a></li>
                        </ul>
                    </div>
                    <div class="col-xs-3 fut1 ">
                        <h4>Features</h4>
                        <ul>
                            <li><a href="/features/">Vultr Cloud Compute (VC2)</a></li>
                            <li><a href="/features/baremetal/">Bare Metal</a></li>
                            <li><a href="/features/blockstorage/">Block Storage</a></li>
                            <li><a href="/features/dedicatedcloud/">Dedicatedd Cloud</a></li>

                        </ul>
                    </div>
                    <div class="col-xs-3 fut1">
                        <h4>Resources</h4>
                        <ul>
                            <li><a href="/faq/">FAQ</a></li>
                            <li><a href="/api/">API</a></li>
                            <li><a href="/docs/">Vultrik Docs</a></li>

                        </ul>
                    </div>
                    <div class="col-xs-3 fut1">
                        <h4>Compan</h4>
                        <ul>
                            <li><a href="/about/">About Us</a></li>
                            <li><a href="/about/team/">Our Team</a></li>
                            <li><a href="/news/">News</a></li>

                        </ul>
                    </div>
                </div>
            </div>
        </footer>
    </div>


    <!-- Bootstrap core JavaScript
================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

</body>

</html>

posts/templates/profile.html
{% extends 'home.html' %}
{% block content %}
    <div class="row clearfix">
        <div class="col-12 columns">
            <form action="post/" method="post">
                {% csrf_token %}
                <div class="col-cm-8 col-cm-offset-2 fieldWrapper">
                    {{ form.text.errors }}
                    {{ form.text }}
                </div>
                <input class="btn btn-primary" type="submit" value="Опубликовать">


            </form>
        </div>
        <div class="col-12 columns">
            {% for post in posts %}
                <div class="bl card  bg-light">
                    {{ post.text }}
                <p></p>
                <p>
                    <i class="icon-user"></i> <a href="/user/{{ user.username }}">{{ user }}</a>
                    | {{ post.created_date | date:"d/m/y" }}
                    | <a href=""><i class="glyphicon glyphicon-comment"></i>Comments</a>
                    | <a href=""><i class="glyphicon glyphicon-share-alt"></i>Shares</a>
                    {% if post.hashtag_set.all|length > 0 %}
                    | <i class="icon-tags"></i> Tags:
                      {% for hashtag in post.hashtag_set.all %}
                          <a href=""><span class="label label-info">{{ hashtag }}</span></a>
                          {% endfor %}
                          {% endif %}
                </p>
                </div>
            {% endfor %}


        </div>
    </div>

{% endblock %}